# vhosts.conf

# [vhost:example.com] or [vhost:*.example.com]
# docroot = htdocs/*/example.com
# python2_enabled = false
# python3_enabled = true
# log_level = normal (quiet, verbose)
# Use {vhost}.log to generate a log sharing the same of it's
# corosponding vhost or name the log file explicitly
# vhost_log = {vhost}.log
# enable_cors = true
# enable_SSL_TLS = false
# leave blank if disabled
# SSL_path =
# TLS_path =


[vhost:default]
docroot = htdocs/default
python2_enabled = false
python3_enabled = false
log_level = quiet
vhost_log = {vhost}.log
enable_cors = false
enable_SSL_TLS = false
# leave blank if disabled
SSL_path =
TLS_path =

[vhost:crest.eveonline.com]
docroot = htdocs/crest/eveonline.com
python2_enabled = false
python3_enabled = false
log_level = verbose
vhost_log = {vhost}.log
enable_cors = false
enable_SSL_TLS = false
# leave blank if disabled
SSL_path =
TLS_path =

[vhost:crest-tq.eveonline.com]
docroot = htdocs/crest-tq/eveonline.com
python2_enabled = false
python3_enabled = false
log_level = normal
vhost_log = {vhost}.log
enable_cors = false
enable_SSL_TLS = false
# leave blank if disabled
SSL_path =
TLS_path =
