# uncompyle6 version 3.3.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
# Embedded file name: d:\BuildAgent\work\f83b6632d72c7b5b\branches\release\EVE-TRANQUILITY\eve\common\modules\usl\eveMimeTypes.py
# Compiled at: 2012-09-22 05:28:41
import mimeTypes
from collections import OrderedDict
ref = mimeTypes.RegisterType('vnd.ccp.eve.Reference-v1', {'href': {'description': 'URI of resource'}, 
   'name': {'description': 'Localized name of resource', 
            'optional': True}, 
   'id': {'description': 'Non-localized name of resource', 
          'optional': True}}, description='A reference to a remote resource contained within the current resource.')
collectionItem = mimeTypes.RegisterType('vnd.ccp.eve.CollectionItem-v1', {'href': {'description': 'URI of this item in collection', 
            'optional': True}, 
   'resource': {'description': 'Reference to resource', 
                'type': mimeTypes.Ref()}})
referenceCollection = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.Collection-v1', collectionItem.attributes, subTypeName=collectionItem.name)
api = mimeTypes.RegisterType('vnd.ccp.eve.Api-v0', {'mediaTypes': {'description': 'Media types used in this API', 
                  'type': mimeTypes.Ref()}, 
   'itemTypes': {'description': 'Item types in the EVE universe, supports id and name filtering', 
                 'type': mimeTypes.Ref()}, 
   'character': {'description': 'Authenticated [[#Character|Character]]', 
                 'type': mimeTypes.Ref(), 
                 'optional': True}, 
   'user': {'description': 'Authenticated user', 
            'type': mimeTypes.Ref()}, 
   'marketGroups': {'description': 'Market Group', 
                    'type': mimeTypes.Ref()}})
userV1 = mimeTypes.RegisterType('vnd.ccp.eve.User-v1', {'mercenaries': {'description': 'List of mercenaries on the user', 
                   'type': mimeTypes.Ref(), 
                   'optional': True}, 
   'notifications': {'description': "The users's notification stream, where all notifications are streamed back on a long standing connection.", 
                     'type': mimeTypes.Ref()}})
itemType = mimeTypes.RegisterType('vnd.ccp.eve.ItemType-v1', {'id': {'description': 'A unique identifier for this item type', 
          'type': long}, 
   'href': {'description': 'A URI for this item', 
            'type': str}, 
   'name': {'description': "The item type's name", 
            'type': str}, 
   'description': {'description': "The item type's description", 
                   'type': str}, 
   'marketGroup': {'description': 'The market group this item belongs to (if any)', 
                   'type': mimeTypes.TypedRef('vnd.ccp.eve.MarketGroup')}, 
   'icon': {'description': 'A non authenticated URI for the items icon', 
            'type': mimeTypes.Ref()}, 
   'attributes': {'description': "The item type's attributes", 
                  'type': mimeTypes.Array({'id': {'description': 'The attribute id', 
                                  'type': long}, 
                           'name': {'description': 'The attribute name', 
                                    'type': str}, 
                           'value': {'description': "The attribute's value", 
                                     'type': mimeTypes.Number}})}})
itemTypeCollection = mimeTypes.RegisterCollectionTypeNew(itemType, denormalize=['name'])
item = mimeTypes.RegisterType('vnd.ccp.eve.Item-v1', {'type': {'description': 'The type of the item', 
            'type': mimeTypes.TypedRef('vnd.ccp.eve.ItemType-v1')}})
capsuleerSkill = mimeTypes.RegisterType('vnd.ccp.eve.CapsuleerSkill-v1', {'href': {'description': 'URI of skill ItemType'}, 
   'self': {'description': 'URI of this sub-object, allowing updates and deletes when aggregated', 
            'optional': True}, 
   'name': {'description': 'Name of skill', 
            'type': str, 
            'optional': True}, 
   'skillPoints': {'description': 'Current skill point count for skill', 
                   'type': int, 
                   'optional': True}, 
   'level': {'description': 'Current skill level', 
             'type': int}})
characterSkillCollection = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.CapsuleerSkillCollection-v1', capsuleerSkill.attributes, subTypeName='vnd.ccp.eve.CapsuleerSkill-v1')
attribute = mimeTypes.RegisterType('vnd.ccp.eve.Attribute-v1', {'id': {'description': 'The non-localized attribute id'}, 
   'name': {'description': 'The localized attribute name'}, 
   'value': {'description': "The attribute's value", 
             'type': int}}, description='A [[#Character|Character]] or item attribute')
corporationV1 = mimeTypes.RegisterType('vnd.ccp.eve.Corporation-v1', {'name': {'description': 'The name of the corporation'}, 
   'ticker': {'description': 'The ticker of the corporation'}, 
   'description': {'description': 'The corporation description'}, 
   'uri': {'description': 'An external information URI for the corporation'}, 
   'taxRate': {'description': 'The tax rate for members of the corporation', 
               'type': float, 
               'default': 0.0, 
               'optional': True}, 
   'acceptApplications': {'description': 'Is the corporation accepting applications', 
                          'type': bool, 
                          'optional': True, 
                          'default': True}, 
   'creator': {'description': 'The [[#Character|Character]] that created the [[#Corporation|Corporation]]', 
               'type': mimeTypes.Ref(), 
               'optional': True}, 
   'ceo': {'description': 'The [[#Character|Character]] currently running the corporation', 
           'type': mimeTypes.Ref(), 
           'optional': True}, 
   'shares': {'description': 'The number of shares that exist for the corporation', 
              'type': int, 
              'optional': True}, 
   'alliance': {'description': 'The alliance which the corporation is a member of', 
                'type': mimeTypes.Ref(), 
                'optional': True}, 
   'contacts': {'description': "The corporation's [[#ContactList|ContactList]]", 
                'type': mimeTypes.Ref()}})
characterAccounts = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.CharacterAccounts', {'ownerID': {'description': 'The ID of the character that owns the account', 
               'type': int}, 
   'keyID': {'description': 'The ID of the wallet level that is being accessed', 
             'type': int}, 
   'balance': {'description': 'The ISK balance present in the wallet', 
               'type': float}, 
   'accountID': {'description': 'The ID of the account in question', 
                 'type': int}})
characterAccountsV2 = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.CharacterAccounts-v2', {'currency': {'description': 'The currency type', 
                'type': str}, 
   'balance': {'description': 'The balance present in the wallet', 
               'type': float}})
beanPickle = mimeTypes.RegisterType('vnd.ccp.eve.BeanPickle', {'beanPickle': {'description': 'A pickled dict', 
                  'type': str}})
corporation = mimeTypes.RegisterType('vnd.ccp.eve.Corporation-v0', {'corporationID': {'description': 'The ID of the corporation', 
                     'type': long, 
                     'optional': True}, 
   'name': {'description': 'The name of the corporation'}, 'ticker': {'description': 'The ticker of the corporation'}, 'description': {'description': 'The corporation description'}, 'url': {'description': 'An external information URL for the corporation'}, 'taxRate': {'description': 'The tax rate for members of the corporation', 
               'type': float, 
               'default': 0.0}, 
   'acceptApplications': {'description': 'Is the corporation accepting applications', 
                          'type': int, 
                          'default': 1}, 
   'battles': {'description': 'A collection of URIs linking to battles that the corporation is involved in', 
               'optional': True}, 
   'members': {'description': 'Corporation members', 
               'optional': True}, 
   'deleted': {'description': 'True if the corporation has been deleted', 
               'optional': True}, 
   'stationID': {'description': 'The ID of the home station of the corporation', 
                 'type': long, 
                 'optional': True}, 
   'creator': {'description': 'A URI to the creating character of the corporation', 
               'type': mimeTypes.TypedRef('vnd.ccp.eve.Character-v1'), 
               'optional': True}, 
   'ceo': {'description': 'A URI to the ceo of the corporation', 
           'type': mimeTypes.TypedRef('vnd.ccp.eve.Character-v1'), 
           'optional': True}, 
   'shares': {'description': 'The number of shares that exist for the corporation', 
              'type': int, 
              'optional': True}, 
   'alliance': {'description': 'A URI to the alliance of which the corporation is a member', 
                'type': mimeTypes.Ref(), 
                'optional': True}})
corporationCollection = mimeTypes.RegisterCollectionType(corporation, (), 'vnd.ccp.eve.CorporationCollection-v0')
dustServerStatus = mimeTypes.RegisterType('vnd.ccp.eve.DustServerStatus', {'status': {'description': 'The server status message'}, 'userCount': {'description': 'Number of online users', 'type': int}, 'edenTime': {'description': 'eve server time in ISO format', 'type': str}, 'motd': {'description': 'Link to the message of the day', 'type': mimeTypes.Ref()}, 'authEndpoint': {'description': 'The URI to use for authentication', 
                    'type': mimeTypes.Dict({'username': {'description': 'The endpoint at which to authenticate by username', 'type': str}})}, 
   'clientVersion': {'description': 'The client version'}, 'serverVersion': {'description': 'The server version'}, 'sentryDSN': {'description': 'Connection string for sentry exception reporting.'}, 'crestEndpoint': {'description': 'Link to the root of the crest API.', 'type': mimeTypes.Ref()}})
mail = mimeTypes.RegisterType('vnd.ccp.eve.Mail-v2', {'href': {'type': str, 
            'optional': True}, 
   'sender': {'type': mimeTypes.TypedRef('vnd.ccp.eve.Character-v1'), 
              'optional': True}, 
   'subject': {'type': unicode}, 
   'sent': {'type': str, 
            'description': 'An ISO-8601 formatted date for when this mail was sent', 
            'optional': True}, 
   'isRead': {'type': bool, 
              'optional': True}, 
   'isReplied': {'type': bool, 
                 'optional': True}, 
   'isForwarded': {'type': bool, 
                   'optional': True}, 
   'isTrashed': {'type': bool, 
                 'optional': True}, 
   'isDraft': {'type': bool, 
               'optional': True}, 
   'isAutomated': {'type': bool, 
                   'optional': True}, 
   'isInbox': {'type': bool, 
               'optional': True}, 
   'isSent': {'type': bool, 
              'optional': True}, 
   'isCorporation': {'type': bool, 
                     'optional': True}, 
   'isAlliance': {'type': bool, 
                  'optional': True}, 
   'isSystem': {'type': bool, 
                'optional': True}, 
   'recipients': {'type': mimeTypes.TypedRefArray('vnd.ccp.eve.Character-v1', attributes={'name': {'type': str, 'optional': True}}), 
                  'optional': True}, 
   'corporation': {'type': mimeTypes.TypedRef('vnd.ccp.eve.Corporation-v1'), 
                   'optional': True}, 
   'alliance': {'type': mimeTypes.TypedRef('vnd.ccp.eve.Alliance-v1'), 
                'optional': True}, 
   'body': {'type': unicode, 
            'optional': True}, 
   'reply': {'type': mimeTypes.TypedRef('vnd.ccp.eve.Mail-v1'), 
             'optional': True}, 
   'forward': {'type': mimeTypes.TypedRef('vnd.ccp.eve.Mail-v1'), 
               'optional': True}})
mailCollection = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.MailCollection-v2', mail.attributes, subTypeName='vnd.ccp.eve.Mail-v2')
region = mimeTypes.RegisterType('vnd.ccp.eve.Region', {'constellations': {'description': 'constellations in this region', 'type': mimeTypes.Ref()}, 'market': {'description': 'market in this region', 'type': mimeTypes.Ref()}})
chatChannel = mimeTypes.RegisterType('vnd.ccp.eve.ChatChannel', {'channelID': {'type': int, 
                 'optional': True, 
                 'description': 'The ID of the channel'}, 
   'channelType': {'type': str, 
                   'optional': False, 
                   'description': 'The type of ID used to specify the channel'}, 
   'displayName': {'type': str, 
                   'optional': True, 
                   'description': 'The user-friendly name to display for the channel'}, 
   'motd': {'type': str, 
            'optional': True, 
            'description': "The channel's Message of the Day"}, 
   'memberless': {'type': bool, 
                  'optional': True, 
                  'description': 'Whether or not the channel is in a memberless state'}, 
   'oldPassword': {'type': str, 
                   'optional': True, 
                   'description': "The channel's old password. Must be provided along with newPassword."}, 
   'newPassword': {'type': str, 
                   'optional': True, 
                   'description': 'The new password to be set for the channel'}, 
   'languageRestriction': {'type': bool, 
                           'optional': True, 
                           'description': 'Whether or not the channel is language restricted'}, 
   'members': {'type': mimeTypes.TypedRef('vnd.ccp.eve.DustUserCharacterItem'), 
               'optional': True, 
               'description': 'A collection of URIs to members of the channel'}, 
   'messages': {'type': mimeTypes.TypedRef('vnd.ccp.eve.ChatMessage'), 
                'optional': True, 
                'description': 'A URI on which one can create messages destined for this channel'}, 
   'creator': {'type': mimeTypes.TypedRef('vnd.ccp.eve.DustUserCharacterItem'), 
               'optional': True, 
               'description': 'A URI to the creating character of this channel'}})
chatChannelV1 = mimeTypes.RegisterType('vnd.ccp.eve.ChatChannel-v1', description='Chat channel information', attributes={'id': {'description': 'The id of this resource', 
          'type': str, 
          'optional': True}, 
   'href': {'description': 'A reference to this chat channel resource', 
            'type': str, 
            'optional': True}, 
   'self': {'description': 'A reference to this sub-object, allowing updates and deletes when aggregated', 
            'type': str, 
            'optional': True}, 
   'name': {'description': 'The user-friendly name to display for the channel', 
            'type': str, 
            'optional': True}, 
   'motd': {'description': "The channel's Message of the Day", 
            'type': str, 
            'optional': True}, 
   'delayedMode': {'description': 'Whether or not the channel is in delayed mode', 
                   'type': bool, 
                   'optional': True}, 
   'password': {'description': "The channel's password. Must be provided along with newPassword when changing the channel's password.", 
                'type': str, 
                'optional': True}, 
   'newPassword': {'description': 'The new password to be set for the channel', 
                   'type': str, 
                   'optional': True}, 
   'languageRestriction': {'description': 'Whether or not the channel is language restricted', 
                           'type': bool, 
                           'optional': True}, 
   'members': {'description': "A refernce to a list of the channel's members", 
               'type': mimeTypes.Ref(), 
               'optional': True}, 
   'memberCount': {'description': 'A count of the number of members in this channel', 
                   'type': int, 
                   'optional': True}})
chatChannels = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.ChatChannelCollection', chatChannelV1.attributes)
chatMessage = mimeTypes.RegisterType('vnd.ccp.eve.ChatMessage', description='A message sent to a chat channel', attributes={'channel': {'description': 'A reference to the channel this message was sent to.', 
               'type': mimeTypes.Ref(), 
               'optional': True}, 
   'message': {'description': 'The text of the message display in a given chat channel', 
               'type': str}})
chatChannelMember = mimeTypes.RegisterType('vnd.ccp.eve.ChatChannelMember', description='Chat channel member information', attributes={'id': {'description': '', 
          'type': str, 
          'optional': True}, 
   'href': {'description': 'A reference to the character', 
            'type': mimeTypes.Ref()}, 
   'self': {'description': 'A reference to this sub-object', 
            'type': mimeTypes.Ref()}, 
   'name': {'description': 'The name of the character', 
            'type': str}, 
   'corporation': {'description': "The character's corporation", 
                   'type': mimeTypes.Ref()}, 
   'alliance': {'description': "The character's alliance", 
                'type': mimeTypes.Ref(), 
                'optional': True}})
chatChannelMembers = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.ChatChannelMemberCollection', chatChannelMember.attributes)
chatChannelKickContext = mimeTypes.RegisterType('vnd.ccp.eve.ChatChannelKickContext', description='Context information for kicking a member from a chat channel', attributes={'reason': {'description': 'A message explaining the reason for kicking the member', 
              'type': str}, 
   'duration': {'description': 'The ban duration in minutes', 
                'type': int}})
chatNotification = mimeTypes.RegisterType('vnd.ccp.eve.OnChatNotification', description='Notification for chat events such as messages received or join/leave notifications', attributes={'channel': {'description': 'A reference to the source channel', 
               'type': mimeTypes.Ref()}, 
   'method': {'description': 'The ', 
              'type': str}, 
   'character': {'description': '', 
                 'type': mimeTypes.Ref()}, 
   'message': {'description': '', 
               'type': str, 
               'optional': True}, 
   'channelType': {'type': str, 'optional': True}, 'channelID': {'type': long, 'optional': True}, 'characterID': {'type': long, 'optional': True}})
inventoryItemDict = {'typeID': {'type': long, 
              'description': 'The typeID of the item in question', 
              'optional': False}, 
   'quantity': {'type': int, 
                'description': 'The number of items of this type in the inventory', 
                'optional': False}}
inventoryItemList = mimeTypes.RegisterType('vnd.ccp.eve.InventoryItemList', {'itemList': {'type': mimeTypes.Array(inventoryItemDict), 
                'description': 'A list of items'}})
inventoryItem = mimeTypes.RegisterType('vnd.ccp.eve.InventoryItem-v1', {'href': {'description': 'URI of this sub-object, allowing updates and deletes when aggregated', 
            'optional': True}, 
   'item': {'type': mimeTypes.Ref(), 
            'description': 'A reference to a more descriptive resource for this item of this type', 
            'optional': True}, 
   'owner': {'type': mimeTypes.Ref(), 
             'description': 'The owner of the item or stack, either a character or a corporation', 
             'optional': True}, 
   'type': {'type': mimeTypes.TypedRef('vnd.ccp.eve.ItemType'), 
            'description': 'The type of the item or stack', 
            'optional': True}, 
   'slot': {'type': str, 
            'description': 'The slot or sublocation of the item or stack', 
            'optional': True}, 
   'stacksize': {'type': int, 
                 'description': 'The number of items in this stack'}})
inventoryItemCollection = mimeTypes.RegisterCollectionType(inventoryItem, name='vnd.ccp.eve.InventoryItemCollection-v1')
mimeTypes.RegisterType('vnd.ccp.eve.OnItemsChanged', OrderedDict([
 (
  'item',
  {'type': mimeTypes.Dict(inventoryItem.attributes), 
     'description': 'list of items with their post-change values set'}),
 (
  'changes',
  {'type': dict, 
     'description': 'a dictionary having as key the attribute name whose value just changed and the pre-change item values as values'})]))
mimeTypes.RegisterType('vnd.ccp.eve.OnDustBattleInventoryChange', OrderedDict([
 (
  'typeID',
  {'type': long, 
     'description': 'The typeID of the item in question', 
     'optional': False}),
 (
  'quantity',
  {'type': int, 
     'description': 'The number of items of this type in the inventory', 
     'optional': False}),
 (
  'charID',
  {'type': long, 
     'description': 'The ID of the Character to which this update pertains', 
     'optional': False})]))
mimeTypes.RegisterType('vnd.ccp.eve.OnAccountChange-v0', OrderedDict([
 (
  'characterID', {}),
 (
  'balance', {})]))
mimeTypes.RegisterType('vnd.ccp.eve.OnAccountChange-v1', OrderedDict([
 (
  'accountType', {}),
 (
  'charID', {}),
 (
  'balance', {})]))
mimeTypes.RegisterType('vnd.ccp.eve.OnProceedBattleConnect', OrderedDict([
 (
  'credential', {}),
 (
  'serverInfo', {}),
 (
  'teamID', {}),
 (
  'battleInfo', {}),
 (
  'battle', {})]))
mimeTypes.RegisterType('vnd.ccp.eve.OnBattleTerminated', OrderedDict([
 (
  'battleID', {}),
 (
  'kickStatus', {}),
 (
  'battle', {})]))
mimeTypes.RegisterType('vnd.ccp.eve.OnCharacterSkillChange', OrderedDict([
 (
  'typeID', {}),
 (
  'level', {}),
 (
  'href', {})]))
mimeTypes.RegisterType('vnd.ccp.eve.OnLSC', OrderedDict([
 (
  'channelType', {'type': str}),
 (
  'channelID', {'type': long}),
 (
  'method', {'type': str}),
 (
  'characterID', {'type': long}),
 (
  'message', {'type': str, 'optional': True})]))
ignoreThisTempAuthType = mimeTypes.RegisterType('vnd.ccp.eve.IgnoreThisTempAuthType', {'access_token': {'description': 'The OAuth access token'}})
mimeTypes.RegisterType('vnd.ccp.dust.BattleMember', {'characterURI': {'description': 'The battle the URI of the player who wishes to join', 'type': mimeTypes.Ref()}, 
   'teamID': {'description': 'The team the player would like to be on. ', 'type': int}})
mimeTypes.RegisterPagedCollection('vnd.ccp.dust.BattleInfoCollection', {'teamID': {'description': 'The team the player would like to be on.', 
              'type': int}, 
   'battleName': {'description': 'The pretty name of the battle', 
                  'type': str}, 
   'status': {'description': 'Status code of the battle', 
              'type': int}, 
   'startTime': {'description': 'Start time of the battle', 
                 'type': int}, 
   'gameModeID': {'description': 'The game mode', 
                  'type': int}, 
   'issuerID': {'description': 'The id of the entity that issued the contract', 
                'type': long}, 
   'attackerID': {'description': 'The id of the corporation sponsoring the attacking team', 
                  'type': long}, 
   'attackerName': {'description': 'The name of the corporation sponsoring the attacking team', 
                    'type': long}, 
   'defenderID': {'description': 'The id of the corporation sponsoring the defending team', 
                  'type': long}, 
   'defenderName': {'description': 'The name of the corporation sponsoring the defending team', 
                    'type': long}, 
   'minPlayersPerTeam': {'description': 'Minimum number of players before the battle will start', 
                         'type': int}, 
   'maxPlayersPerTeam': {'description': 'Maximum number of players there can join the battle', 
                         'type': int}, 
   'curPlayersTeam0': {'description': 'Number of players on the attacking team', 
                       'type': int}, 
   'curPlayersTeam1': {'description': 'Number of players on the defending team', 
                       'type': int}, 
   'useWarRoomTime': {'description': 'The time the war room is open before the battle starts', 
                      'type': int}, 
   'lightingMood': {'description': 'The lightning scheme used in the battle', 
                    'type': int}, 
   'battleType': {'description': 'The battle type', 
                  'type': int}, 
   'assetURI': {'description': 'The URI to all assets required to launch this map', 
                'type': mimeTypes.Ref()}})
_MIME_TYPE_DUST_USER_CHARACTER_ITEM = 'vnd.ccp.eve.DustUserCharacterItem'
dustCharacter = mimeTypes.RegisterType(_MIME_TYPE_DUST_USER_CHARACTER_ITEM, {'characterName': {'type': str, 
                     'description': 'Character Name'}, 
   'gender': {'type': int, 
              'description': 'Is character Male?'}, 
   'bloodlineID': {'type': int, 
                   'description': 'Character bloodline'}, 
   'specialtyID': {'type': int, 
                   'description': 'Specialty ID'}, 
   'createDate': {'type': int, 
                  'optional': True, 
                  'description': 'When was this character created?'}, 
   'corporationName': {'type': str, 
                       'optional': True, 
                       'description': ''}, 
   'corporationID': {'type': int, 
                     'optional': True, 
                     'description': 'The internal ID of the corporation which the character is a member of'}, 
   'characterID': {'type': int, 
                   'optional': True, 
                   'description': 'The internal ID of the Character'}, 
   'wallet': {'optional': True, 
              'description': 'The link to the wallet information for the character'}, 
   'contactListURI': {'optional': True, 
                      'description': 'The link to the contact information for the character'}, 
   'blockedListURI': {'optional': True, 
                      'description': 'The link for blocked list info for the character'}, 
   'transactionURI': {'optional': True, 
                      'description': 'The link to get transaction history data for the character'}, 
   'fittingURI': {'optional': True, 
                  'description': 'The link to the fitting2 information for the character'}, 
   'inventoryURI': {'optional': True, 
                    'description': 'The link to the inventory information for the character'}, 
   'battleInventoryURI': {'optional': True, 
                          'description': 'The link to the inventory information for the character in battle'}, 
   'totalSkillPoints': {'optional': True, 
                        'description': 'Total skillpoints earned by the character so far', 
                        'type': long}, 
   'skillPointsPerDay': {'optional': True, 
                         'description': 'Number of skill points the character should gain passively per day', 
                         'type': long}, 
   'skillURI': {'optional': True, 
                'description': 'The link to the skill information for the character'}, 
   'availableSkillsURI': {'optional': True, 
                          'description': 'The link to get known skills and skills you can buy a book and learn'}, 
   'skillBoosterURI': {'optional': True, 
                       'description': 'The link to the skill booster for a character'}, 
   'corporationURI': {'optional': True, 
                      'description': "The link to the character's corporation"}, 
   'lifetimeStatsURI': {'optional': True, 
                        'description': "The link to the character's lifetime stats"}, 
   'fulfillmentsURI': {'optional': True, 
                       'description': "The link to the user's fulfillments"}, 
   'redeemURI': {'optional': True, 
                 'description': "The link to the character's redemption"}, 
   'vivoxURI': {'optional': True, 
                'description': "The link to the character's voice chat info"}, 
   'portraitID': {'type': int, 
                  'optional': True, 
                  'description': 'An index for a static portrait'}, 
   'marketBuyOrderUri': {'optional': True, 
                         'description': 'The link to buy orders in market'}, 
   'marketSellOrderUri': {'optional': True, 
                          'description': 'The link to sell orders in market'}, 
   'marketRegionPrices': {'optional': True, 
                          'description': 'The link to market region prices'}, 
   'marketStorefront': {'optional': True, 
                        'description': 'The link to the market store front'}})
dustCharacterCollection = mimeTypes.RegisterCollectionType(dustCharacter, ('characterName',
                                                                           'characterID'))
_MIME_TYPE_DUST_USER_ITEM = 'vnd.ccp.eve.DustUserItem'
dustUser = mimeTypes.RegisterType(_MIME_TYPE_DUST_USER_ITEM, {'characters': {'description': 'Link to the DustUserCharacter Collection.', 'type': mimeTypes.Ref()}, 'currentCharacter': {'description': 'Link to the currently selected character', 'type': mimeTypes.Ref()}})
mimeTypes.RegisterCollectionType(mimeTypes.RegisterType('vnd.ccp.eve.DustSkillBooster', {'kind': {'description': 'The kind of skill gain this booster affects {0: passive, 1: active}', 'type': int}, 'multiplier': {'description': 'The multiplier this booster provides', 'type': float}, 'expirationDate': {'description': 'The date when this booster will expire', 'type': unicode}, 'href': {'description': 'URI for this individual booster', 'type': unicode}}), ('kind',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'multiplier',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'expirationDate',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'href'))
mimeTypes.RegisterType('vnd.ccp.dust.Skill', {'skillTypeID': {'description': 'The typeID of the skill.', 
                   'type': int}})
mimeTypes.RegisterCollectionType(mimeTypes.RegisterType('vnd.ccp.eve.DustCharacterSkill', {'skillTypeID': {'description': 'The skill type ID', 'type': long}, 'skillName': {'description': 'The skill name', 'type': unicode}, 'skillLevel': {'description': 'What level this skill is trained to', 'type': int}, 'href': {'description': 'URI for this individual skill', 'type': unicode}}), ('skillTypeID',
                                                                                                                                                                                                                                                                                                                                                                                                'skillName',
                                                                                                                                                                                                                                                                                                                                                                                                'skillLevel',
                                                                                                                                                                                                                                                                                                                                                                                                'href'), name='vnd.ccp.eve.DustCharacterSkillCollection')
mimeTypes.RegisterCollectionType(mimeTypes.RegisterType('vnd.ccp.dust.TrainedSkill', {'skillTypeID': {'description': 'The typeID of the skill.', 
                   'type': long}, 
   'skillLevel': {'description': 'To which level the skill is trained', 
                  'type': int}}), ('skillTypeID', 'skillLevel'))
mimeTypes.RegisterType('vnd.ccp.dust.OnClusterControllerLogin', {})
mimeTypes.RegisterType('vnd.ccp.dust.OnClusterSendAddressPortBack', {'battleID': {'description': 'The battleID of the server.', 'type': long}, 
   'address': {'description': 'battle server address.', 'type': str}, 
   'port': {'description': 'battle server port.', 'type': int}})
matchEndResult = mimeTypes.RegisterType('vnd.ccp.dust.MatchEndResult', {'battleID': {'description': 'The battle that was fought.', 'type': long}, 
   'winnerTeamID': {'description': 'The team who won.', 'type': long}, 
   'totalConsumption': {'description': 'The value of all items lost in the battle.', 'type': float}, 
   'characterResults': {'description': 'List with the result data from the character.', 'type': mimeTypes.Array({'characterID': {'description': 'CharacterID of the rewarded player.', 'type': long}, 
                                 'warPoints': {'description': 'Number of war points at the end of the match.', 'type': float}, 
                                 'isOnWinningTeam': {'description': 'Was the player on the winning team or not.', 'type': bool}, 
                                 'teamContribution': {'description': 'A float between 0 and 1 of how much contribution this player has made.', 'type': float}})}})
matchEndResponse = mimeTypes.RegisterPagedCollection('vnd.ccp.dust.MatchEndResponse', {'characterID': {'description': 'CharacterID of the rewarded player.', 
                   'type': long}, 
   'skillPoints': {'description': 'Number of skill points rewarded to the player.', 
                   'type': long}, 
   'modifierBonus': {'description': "Number of skill points that were granted due to boosters.  Note that these are already included in 'skillPoints'.", 
                     'type': long}, 
   'ISKReward': {'description': 'Amount of ISK rewarded to the player.', 
                 'type': float}, 
   'LootReward': {'description': 'List of items as loot rewards to the player.', 
                  'type': mimeTypes.Array({'href': {'description': 'reference to reward item.', 'type': mimeTypes.Ref()}, 'typeID': {'description': 'reward item typeID.', 'type': long}, 'quantity': {'description': 'number of item rewareded', 'type': int}})}})
characterEntitlement = mimeTypes.RegisterType('vnd.ccp.dust.CharacterEntitlement', {'ticket': {'description': 'The PSN ticket carrying the entitlements that are to be consumed'}})
dustVivoxInfo = mimeTypes.RegisterType('vnd.ccp.dust.VivoxInfo', {'vivoxUsername': {'optional': False, 
                     'description': 'Username with which this character may log into Vivox'}, 
   'vivoxPassword': {'optional': False, 
                     'description': 'Password with which this character may log into Vivox'}, 
   'vivoxServer': {'optional': False, 
                   'description': 'Hostname (DNS or IP) of the server to which the client should connect for Vivox voice support'}})
dustQuickMatchInfo = mimeTypes.RegisterType('vnd.ccp.dust.QuickMatchInfo', {'ttl': {'description': 'Time-to-live, i.e. how long in seconds the entry stays in the queue.', 'type': float}, 
   'playersInQueue': {'description': 'Number of players currently in match-making queue.', 'type': int}})
dustContactList = mimeTypes.RegisterType('vnd.ccp.eve.DustContactList', {'contactURI': {'description': 'URI to get/delete in contact list', 
                  'type': mimeTypes.Ref(), 
                  'optional': True}, 
   'watchListURI': {'description': 'URI to post/delete contact from watched list', 
                    'type': mimeTypes.Ref(), 
                    'optional': True}, 
   'characterURI': {'description': 'Character URI of contact', 
                    'type': mimeTypes.Ref()}, 
   'characterName': {'description': 'Name of contact', 
                     'type': unicode, 
                     'optional': True}, 
   'corporationURI': {'description': 'Corporation URI of contact', 
                      'type': mimeTypes.Ref(), 
                      'optional': True}, 
   'corporationName': {'description': 'Corporation Name of contact', 
                       'type': unicode, 
                       'optional': True}, 
   'portraitURI': {'description': 'Portrait URI of contact', 
                   'type': mimeTypes.Ref(), 
                   'optional': True}, 
   'battleURI': {'description': 'Battle URI of contact', 
                 'type': mimeTypes.Ref(), 
                 'optional': True}, 
   'isDust': {'description': 'Flag indicating if the contact is a Dust character', 
              'type': bool, 
              'optional': True}, 
   'online': {'description': 'Flag indicating if the contact is online', 
              'type': bool, 
              'optional': True}, 
   'watched': {'description': 'Flag indicating if the contact is on the watch list', 
               'type': bool, 
               'optional': True}, 
   'logoffDate': {'type': str, 
                  'description': 'An ISO-8601 formatted date for the last time the user logged off', 
                  'optional': True}}, description='A [[#Character|Character]] contact')
dustContactListCollection = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.DustContactListCollection', dustContactList.attributes, subTypeName='vnd.ccp.eve.DustContactList')
dustBlockedList = mimeTypes.RegisterType('vnd.ccp.eve.DustBlockedList', {'blockedContactURI': {'description': 'URI to get/delete in blocked list', 
                         'type': mimeTypes.Ref(), 
                         'optional': True}, 
   'characterURI': {'description': 'Character URI of contact', 
                    'type': mimeTypes.Ref()}, 
   'characterName': {'description': 'Name of contact', 
                     'type': unicode, 
                     'optional': True}, 
   'corporationURI': {'description': 'Corporation URI of contact', 
                      'type': mimeTypes.Ref(), 
                      'optional': True}, 
   'corporationName': {'description': 'Corporation Name of contact', 
                       'type': unicode, 
                       'optional': True}, 
   'portraitURI': {'description': 'Portrait URI of contact', 
                   'type': mimeTypes.Ref(), 
                   'optional': True}, 
   'battleURI': {'description': 'Battle URI of contact', 
                 'type': mimeTypes.Ref(), 
                 'optional': True}, 
   'isDust': {'description': 'Flag indicating if the contact is a Dust character', 
              'type': bool, 
              'optional': True}, 
   'online': {'description': 'Flag indicating if the contact is online', 
              'type': bool, 
              'optional': True}, 
   'logoffDate': {'type': str, 
                  'description': 'An ISO-8601 formatted date for the last time the user logged off', 
                  'optional': True}}, description='A blocked [[#Character|Character]]')
dustBlockedListCollection = mimeTypes.RegisterPagedCollection('vnd.ccp.eve.DustBlockedListCollection', dustBlockedList.attributes, subTypeName='vnd.ccp.eve.DustBlockedList')
dustAccountJournalHistory = mimeTypes.RegisterType('vnd.ccp.eve.DustAccountJournalHistory', {'transactionID': {'description': 'The ID of the transaction'}, 
   'description': {'description': 'The description of the transaction'}, 
   'transactionDate': {'description': 'The date of the transaction'}, 
   'amount': {'description': 'The amount of the transaction'}, 
   'balance': {'description': 'Balance after transaction'}}, description='Journal history')